/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface StateswapRegistryInterface extends utils.Interface {
  functions: {
    "DELAY_PERIOD()": FunctionFragment;
    "contracts(address)": FunctionFragment;
    "delegateProxyImplementation()": FunctionFragment;
    "endGrantAuthentication(address)": FunctionFragment;
    "initialAddressSet()": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "pending(address)": FunctionFragment;
    "proxies(address)": FunctionFragment;
    "registerProxy()": FunctionFragment;
    "registerProxyFor(address)": FunctionFragment;
    "registerProxyOverride()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeAuthentication(address)": FunctionFragment;
    "startGrantAuthentication(address)": FunctionFragment;
    "transferAccessTo(address,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "grantInitialAuthentication(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DELAY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "contracts", values: [string]): string;
  encodeFunctionData(
    functionFragment: "delegateProxyImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endGrantAuthentication",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialAddressSet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pending", values: [string]): string;
  encodeFunctionData(functionFragment: "proxies", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProxyFor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProxyOverride",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuthentication",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "startGrantAuthentication",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAccessTo",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantInitialAuthentication",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DELAY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegateProxyImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endGrantAuthentication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialAddressSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proxies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProxyFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProxyOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuthentication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startGrantAuthentication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAccessTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantInitialAuthentication",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface StateswapRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StateswapRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DELAY_PERIOD(overrides?: CallOverrides): Promise<[BigNumber]>;

    contracts(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    delegateProxyImplementation(overrides?: CallOverrides): Promise<[string]>;

    /**
     * ProxyRegistry owner only
     * End the process to enable access for specified contract after delay period has passed.
     * @param addr Address to which to grant permissions
     */
    endGrantAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialAddressSet(overrides?: CallOverrides): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    pending(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    proxies(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry
     */
    registerProxy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Can be called by any user
     * Register a proxy contract with this registry
     */
    registerProxyFor(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry, overriding any existing proxy
     */
    registerProxyOverride(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * ProxyRegistry owner only
     * Revoke access for specified contract. Can be done instantly.
     * @param addr Address of which to revoke permissions
     */
    revokeAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * ProxyRegistry owner only
     * Start the process to enable access for specified contract. Subject to delay period.
     * @param addr Address to which to grant permissions
     */
    startGrantAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Transfer access
     */
    transferAccessTo(
      from: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * No delay, can only be called once - after that the standard registry process with a delay must be used
     * Grant authentication to the initial Exchange protocol contract
     * @param authAddress Address of the contract to grant authentication
     */
    grantInitialAuthentication(
      authAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DELAY_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

  contracts(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  delegateProxyImplementation(overrides?: CallOverrides): Promise<string>;

  /**
   * ProxyRegistry owner only
   * End the process to enable access for specified contract after delay period has passed.
   * @param addr Address to which to grant permissions
   */
  endGrantAuthentication(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialAddressSet(overrides?: CallOverrides): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  /**
   * Returns the address of the current owner.
   */
  owner(overrides?: CallOverrides): Promise<string>;

  pending(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  proxies(arg0: string, overrides?: CallOverrides): Promise<string>;

  /**
   * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
   * Register a proxy contract with this registry
   */
  registerProxy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Can be called by any user
   * Register a proxy contract with this registry
   */
  registerProxyFor(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
   * Register a proxy contract with this registry, overriding any existing proxy
   */
  registerProxyOverride(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * ProxyRegistry owner only
   * Revoke access for specified contract. Can be done instantly.
   * @param addr Address of which to revoke permissions
   */
  revokeAuthentication(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * ProxyRegistry owner only
   * Start the process to enable access for specified contract. Subject to delay period.
   * @param addr Address to which to grant permissions
   */
  startGrantAuthentication(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Transfer access
   */
  transferAccessTo(
    from: string,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * No delay, can only be called once - after that the standard registry process with a delay must be used
   * Grant authentication to the initial Exchange protocol contract
   * @param authAddress Address of the contract to grant authentication
   */
  grantInitialAuthentication(
    authAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DELAY_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    contracts(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    delegateProxyImplementation(overrides?: CallOverrides): Promise<string>;

    /**
     * ProxyRegistry owner only
     * End the process to enable access for specified contract after delay period has passed.
     * @param addr Address to which to grant permissions
     */
    endGrantAuthentication(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialAddressSet(overrides?: CallOverrides): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<string>;

    pending(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    proxies(arg0: string, overrides?: CallOverrides): Promise<string>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry
     */
    registerProxy(overrides?: CallOverrides): Promise<string>;

    /**
     * Can be called by any user
     * Register a proxy contract with this registry
     */
    registerProxyFor(user: string, overrides?: CallOverrides): Promise<string>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry, overriding any existing proxy
     */
    registerProxyOverride(overrides?: CallOverrides): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    /**
     * ProxyRegistry owner only
     * Revoke access for specified contract. Can be done instantly.
     * @param addr Address of which to revoke permissions
     */
    revokeAuthentication(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * ProxyRegistry owner only
     * Start the process to enable access for specified contract. Subject to delay period.
     * @param addr Address to which to grant permissions
     */
    startGrantAuthentication(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Transfer access
     */
    transferAccessTo(
      from: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * No delay, can only be called once - after that the standard registry process with a delay must be used
     * Grant authentication to the initial Exchange protocol contract
     * @param authAddress Address of the contract to grant authentication
     */
    grantInitialAuthentication(
      authAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    DELAY_PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    contracts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    delegateProxyImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * ProxyRegistry owner only
     * End the process to enable access for specified contract after delay period has passed.
     * @param addr Address to which to grant permissions
     */
    endGrantAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialAddressSet(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pending(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    proxies(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry
     */
    registerProxy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Can be called by any user
     * Register a proxy contract with this registry
     */
    registerProxyFor(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry, overriding any existing proxy
     */
    registerProxyOverride(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * ProxyRegistry owner only
     * Revoke access for specified contract. Can be done instantly.
     * @param addr Address of which to revoke permissions
     */
    revokeAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * ProxyRegistry owner only
     * Start the process to enable access for specified contract. Subject to delay period.
     * @param addr Address to which to grant permissions
     */
    startGrantAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Transfer access
     */
    transferAccessTo(
      from: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * No delay, can only be called once - after that the standard registry process with a delay must be used
     * Grant authentication to the initial Exchange protocol contract
     * @param authAddress Address of the contract to grant authentication
     */
    grantInitialAuthentication(
      authAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DELAY_PERIOD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contracts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegateProxyImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * ProxyRegistry owner only
     * End the process to enable access for specified contract after delay period has passed.
     * @param addr Address to which to grant permissions
     */
    endGrantAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialAddressSet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Returns the address of the current owner.
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pending(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxies(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry
     */
    registerProxy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Can be called by any user
     * Register a proxy contract with this registry
     */
    registerProxyFor(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Must be called by the user which the proxy is for, creates a new AuthenticatedProxy
     * Register a proxy contract with this registry, overriding any existing proxy
     */
    registerProxyOverride(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * ProxyRegistry owner only
     * Revoke access for specified contract. Can be done instantly.
     * @param addr Address of which to revoke permissions
     */
    revokeAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * ProxyRegistry owner only
     * Start the process to enable access for specified contract. Subject to delay period.
     * @param addr Address to which to grant permissions
     */
    startGrantAuthentication(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Transfer access
     */
    transferAccessTo(
      from: string,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * No delay, can only be called once - after that the standard registry process with a delay must be used
     * Grant authentication to the initial Exchange protocol contract
     * @param authAddress Address of the contract to grant authentication
     */
    grantInitialAuthentication(
      authAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
